Bugfix: Need to underscore project name to form wheel path.

diff --git a/bin/release-ghub-pypi b/bin/release-ghub-pypi
--- a/bin/release-ghub-pypi
+++ b/bin/release-ghub-pypi
@@ -1448,16 +1448,18 @@ github_release_release () {
   # (lb): There's really no reason to upload the wheel file.
   # And no reason not to. I think I'm inclined to do so just
   # to be complete.
+  # Note that the wheel name is the underscored project name.
+  local wheel_file
   let 'num_uploaded = 0' || true  # A '0' from let equates to false, who knew!
-  for pyvers in "py3" "py2.py3"; do
-    local wheel_file
-    wheel_file="dist/${PYPI_PACKAGE}-${RELEASE_VERSION}-${pyvers}-none-any.whl"
+  for pyvers in "py2.py3" "py3"; do
+    wheel_file="dist/${PYPI_PROJECT//-/_}-${RELEASE_VERSION}-${pyvers}-none-any.whl"
     github_upload_file "${wheel_file}" && let 'num_uploaded += 1' || true
   done
   if [ ${num_uploaded} -ne 1 ]; then
     # 2020-03-28: (lb): Not sure this is fatal or not. At least message.
     >&2 echo
-    >&2 echo "ERROR: Did not upload one wheel file... check under dist/."
+    >&2 echo "ERROR: Did not upload one wheel file... check under dist/. E.g.,"
+    >&2 echo "         ${wheel_file}"
     >&2 echo
   fi
 }
