Improve: Deduce dependency fallback paths from executable's.

diff --git a/bin/release-ghub-pypi b/bin/release-ghub-pypi
--- a/bin/release-ghub-pypi
+++ b/bin/release-ghub-pypi
@@ -61,28 +61,39 @@ setup_project_vars () {
 # ###
 
 source_deps () {
+  local thispth="$1"
+  local prefix=""
   local depsnok=false
 
   _source_it () {
-    local file="$1"
-    if [ -f "./deps/${file}" ]; then
-      # E.g., because `bpkg install landonb/release-ghub-pypi`.
-      . "./deps/${file}"
-    elif command -v "${file}" > /dev/null; then
-      # E.g., because on PATH.
+    local prfx="${1:-.}"
+    local depd="${2:-.}"
+    local file="${3:-.}"
+    local path="${prfx}/${depd}/${file}"
+    if command -v "${file}" > /dev/null; then
+      # Use version found on PATH.
       . "${file}"
+    elif [ -f "${path}" ]; then
+      # Fallback on local deps/ copy.
+      # NOTE: `dash` complains if missing './'.
+      . "${path}"
     else
-      >&2 echo "MISSING: ‘${file}’ not found in ./deps or on PATH."
+      local depstxt=''
+      [ "${prfx}" != "." ] && depstxt="in ‘${prfx}/${depd}’ or "
+      >&2 echo "MISSING: ‘${file}’ not found ${depstxt}on PATH."
       depsnok=true
     fi
   }
 
-  # https://github.com/landonb/sh-colors
-  _source_it "colors.sh"
-  # https://github.com/landonb/sh-logger
-  _source_it "logger.sh"
+  # Allow user to symlink executables and not libraries.
+  prefix="$(dirname -- "$(readlink -e -- "${thispth}")")"
 
-  ${depsnok} && exit 1 || return 0
+  # https://github.com/landonb/sh-colors
+  _source_it "${prefix}" "../deps/sh-colors/bin" "colors.sh"
+  # https://github.com/landonb/sh-logger
+  _source_it "${prefix}" "../deps/sh-logger/bin" "logger.sh"
+
+  ! ${depsnok}
 }
 
 # ###
@@ -1711,7 +1722,6 @@ release-ghub-pypi () {
   set -e
   ensure_vars
   cd "${PROJECT_PATH}"
-  source_deps
   suss_piping
   must_prereqs_system
   release_project
@@ -1721,13 +1731,15 @@ release-ghub-pypi () {
 
 # ***
 
-if [[ ${BASH_SOURCE[0]} != $0 ]]; then
+source_deps "${BASH_SOURCE[0]}"
+unset -f source_deps
+
+if [ "${BASH_SOURCE[0]}" != "$0" ]; then
   # SKIP: (because user should write their own):
   #   export -f setup_project_vars
   export -f release-ghub-pypi
 else
   setup_project_vars
   release-ghub-pypi "${@}"
-  exit $?
 fi
 
